"""Customer-facing quotation document export (print-ready HTML).

Follows the setup_sheet pattern: self-contained HTML with print CSS so the
shop can save it, email it, or print-to-PDF from the browser — no extra
Python dependencies required.
"""
from __future__ import annotations
from datetime import date


def generate_quote_html(quote: dict) -> str:
    """Render a quotation as a standalone printable HTML document.

    quote keys (all optional except cost_rows):
        shop_name, shop_contact          — header identity
        customer_name                    — addressee
        part_name, material, machine     — job summary
        stock_dims, batch_qty            — job summary
        machine_time_min                 — time summary
        cost_rows  : list of (label, value) tuples in display order
        currency   : symbol prefix for values, e.g. "₹" or "$"
        sell_price : headline per-part price (float)
        quote_ref  : reference string
        validity_days : quote validity (default 30)
        notes      : free-text terms/notes
    """
    sym = quote.get("currency", "₹")
    rows_html = "\n".join(
        f"<tr><td>{label}</td><td class='num'>{sym}{value:,.2f}</td></tr>"
        for label, value in quote.get("cost_rows", [])
    )
    sell = quote.get("sell_price")
    sell_html = f"{sym}{sell:,.2f}" if sell is not None else "—"
    batch = quote.get("batch_qty", 1)
    t_min = quote.get("machine_time_min")
    time_html = f"{t_min:.0f} min ({t_min / 60.0:.2f} h)" if t_min else "—"

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Quotation {quote.get('quote_ref', '')}</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #222; margin: 40px; }}
  h1 {{ font-size: 22px; border-bottom: 3px solid #1a73e8; padding-bottom: 8px; }}
  .meta, .job {{ width: 100%; margin: 14px 0; border-collapse: collapse; }}
  .meta td {{ padding: 3px 8px 3px 0; font-size: 13px; }}
  table.cost {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
  table.cost td, table.cost th {{ border: 1px solid #ccc; padding: 6px 10px; font-size: 13px; }}
  table.cost th {{ background: #f0f4ff; text-align: left; }}
  td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
  tr:last-child td {{ font-weight: 700; background: #f6ffed; }}
  .price {{ font-size: 26px; font-weight: 700; color: #1a73e8; margin: 16px 0 4px; }}
  .small {{ font-size: 11px; color: #777; margin-top: 24px; }}
  @media print {{ body {{ margin: 12mm; }} }}
</style></head><body>
<h1>{quote.get('shop_name', 'CNC Machining Quotation')}</h1>
<table class="meta">
  <tr><td><b>Quote ref:</b> {quote.get('quote_ref', '—')}</td>
      <td><b>Date:</b> {date.today().isoformat()}</td>
      <td><b>Valid:</b> {quote.get('validity_days', 30)} days</td></tr>
  <tr><td><b>Customer:</b> {quote.get('customer_name', '—')}</td>
      <td><b>Contact:</b> {quote.get('shop_contact', '—')}</td><td></td></tr>
</table>
<table class="meta job">
  <tr><td><b>Part:</b> {quote.get('part_name', '—')}</td>
      <td><b>Material:</b> {quote.get('material', '—')}</td></tr>
  <tr><td><b>Stock:</b> {quote.get('stock_dims', '—')}</td>
      <td><b>Machine:</b> {quote.get('machine', '—')}</td></tr>
  <tr><td><b>Batch quantity:</b> {batch}</td>
      <td><b>Est. machine time / part:</b> {time_html}</td></tr>
</table>
<table class="cost">
  <tr><th>Cost item</th><th>Per part</th></tr>
  {rows_html}
</table>
<div class="price">Sell price per part: {sell_html}</div>
<div>Batch total ({batch} pcs): {sym}{(sell or 0) * batch:,.2f}</div>
<div class="small">
  {quote.get('notes', 'Prices exclude GST and shipping unless stated. '
   'Quotation generated by CNC Plan and Process Pro — estimates are for '
   'planning; final price may vary after drawing review.')}
</div>
</body></html>"""
